### ISSUE TITLE
Integrate with Firefly SDK Core features

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/aem-headless-client-js#13]
Looking at the possibility to use the SDK within a Project Firefly app (e.g. for server-side rendering use-cases), it should be integrated with [Project Firefly Core SDK](https://github.com/adobe/aio-sdk-core) for a more streamlined developer experience.

Thinking particularly about the following Node modules:

- `aio-lib-core-config` to manage persistent and environment variable configuration
- `aio-lib-core-logging` to manage logging
- `aio-lib-core-errors` to manage error handling
- Possibly `aio-lib-core-networking` to manage http requests with exponential backoff

Note: this suggested enhancement doesn't apply for client-side usage of this SDK.

**Comment by bdelacretaz** [comment]
To avoid having too many dependencies when using this library in a client browser, it might be worth having two variants, a slim client-side one with minimal dependencies and a server-side variant meant for use in I/O Runtime Actions for Firefly, that can have more dependencies. We need to dig deeper to find out how to best structure this.

**Comment by meryllblanchet** [comment]
@shazron started looking at it this week as well and will provide feedback soon.

**Comment by shazron** [comment]
> two variants, a slim client-side one with minimal dependencies and a server-side variant meant for use in I/O Runtime Actions for Firefly, that can have more dependencies

This is definitely a good plan. 

monorepo or separate repos? We could have these two variants sharing one repo (a monorepo), and shared using [npm workspaces](https://dev.to/limal/simplify-your-monorepo-with-npm-7-workspaces-5gmj)  They still would be independent npm packages and are released separately. 

The only benefit I see is ease of development (we wouldn't have to npm link etc dependent modules) but that is not a big concern unless we have more than one shared module.

I think sticking to a one-package-one-repo model simplifies things -- issues and PRs do not have to be tagged to the appropriate module, clarity on the purpose of the repo vs a [monorepo](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk), so my vote is on one-package-one-repo.

We have something done something similar with [aio-lib-runtime, a node.js module](https://github.com/adobe/aio-lib-runtime) using [openwhisk-js, a Javascript library](https://github.com/apache/openwhisk-client-js).

**Comment by meryllblanchet** [comment]
Thanks @shazron ! @bdelacretaz how do you feel with the suggested approach (which confirms your initial thoughts)?

**Comment by bdelacretaz** [comment]
Thanks @shazron for the input, I agree and generally prefer the _one-package-one-repo_ model. That's how Apache Sling proudly grew to more than 300 repositories ;-)

Provided the repositories are linked in an obvious way (also using GitHub Topics) I think that's easy to manage.

**Comment by meryllblanchet** [comment]
@bdelacretaz did you move forward with the creation of the repository for the node.js module?

**Comment by bdelacretaz** [comment]
I have requested the creation of https://github.com/adobe/aem-headless-client-nodejs , should be up soon

**Comment by meryllblanchet** [comment]
I'll close this issue and we can follow up on https://github.com/adobe/aem-headless-client-nodejs/issues/1 directly.
