### ISSUE TITLE
runPersistedQuery is not being able to handle multiple variables

### ISSUE THREAD

**Issue by opapito** [adobe/aem-headless-client-js#28]
### Expected Behaviour
runPersistedQuery should be able to **handle multiple variables** as per API documentation

### Actual Behaviour
When running a persisted query with more the one variable in an HTTP GET method, the resulting variablesString in the actual code causes a ServletError 

#### Steps to Reproduce
(1) persist a query with **more than one** variable
(2) call runPersistedQuery with a valid path and more than one variable in parameters
(3) __handleRequest will throw a general request error

#### Platform and Version
Windows 10 Pro, 21H2, 19044.1387, Windows Feature Experience Pack 120.2212.3920.0
Adobe Experience Manager 6.5.10.0

#### Sample Code that illustrates the problem
const { data, errors } = useGraphQL('', '/wknd/some-persisted-query', {fragmentPath : _path, includeJson:includeJson} );

**Comment by easingthemes** [comment]
Fixed with related PR
