### ISSUE TITLE
string variable incorrectly stringified

### ISSUE THREAD

**Issue by gregal** [adobe/aem-headless-client-js#51]
### Expected Behaviour

When passing a string variable to `runPersistedQuery`, `variablesString` should be formatted without underquoting it.

Example:

```typescript
const variables = { slug: 'aaa' }
await aemHeadlessClient.runPersistedQuery(path, variables)
```

`variablesString` should finally be assigned:

```typescript
';slug=aaa'
```

as it is under `@adobe/aem-headless-client-js@3.2.0`.

### Actual Behaviour

`variablesString` is assigned:

```typescript
';slug="aaa"'
```

...with the extra double quotes. Apparently, a bug introduced in #41.

#### Platform and Version

`@adobe/aem-headless-client-js@3.3.0` and `3.3.1`

**Comment by cpilsworth** [comment]
I think this problem was introduced in [#50 here](https://github.com/adobe/aem-headless-client-js/pull/50/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R108)
Its correct for an object 
```js
JSON.stringify({hello: "world"}) == '{"hello":"world"}'
```
but not for a simple string value
```js
JSON.stringify("hello") == '"hello"'
```

**Comment by petergray-maker** [comment]
This is also affecting my project, it looks like [the ](https://github.com/adobe/aem-headless-client-js/pull/53) is all good to be merged? Can it please be applied ?

Cheers
